version: '3.0' # Docker-compose version number

# Define the containers to be run
services:
  angular:
    build: client
    ports:
      - "4200:4200"
    container_name: "client"
    # Tag our image with the current build version
    image: "mikemcjay/rate-a-tune-client:1.4.0"

  express:
    build: server
    ports:
      - "3000:3000"
    container_name: "server"
    # Tag our image with the current build version
    image: "mikemcjay/rate-a-tune-server:1.4.0"

  database:
    image: mongo # Pull the latest mongo docker image
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: